### ISSUE TITLE
Fehler beim Installieren des PlugIn "Server"

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/project_manager#10]
Ich habe hier ein aktuelles Redaxo 5.6.4. und wollte mir das AddOn mal eben anschauen, scheitere aber bei der Installation des PlugIns "Server".

PlugIn server konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "CREATE TABLE `rex_project_manager_domain` ( `id` int(10) unsigned NOT NULL auto_increment, `name` varchar(255) , `domain` varchar(255) , `api_key` varchar(32) , `is_ssl` tinyint , `description` text NOT NULL , `cms` tinyint , `status` text NOT NULL , `createdate` timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL default CURRENT_TIMESTAMP, `updatedate` timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL on update CURRENT_TIMESTAMP, `logdate` timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL default CURRENT_TIMESTAMP, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;"! SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Nunja, ich hoffe das hilft...!?

**Comment by staabm** [comment]
Vermutlich hängt das mit der mysql version zusammen

**Comment by dpf-dd** [comment]
Das könnte sein, das Zeuch liegt noch auf einer relativ alten Umgebung:
PHP 5.6.35
MySQL 5.5.59-0ubuntu0.14.04.1

**Comment by rkemmere** [comment]
Die Limitierung wurde 2012 geändert.

Changes in MySQL 5.6.5 (2012-04-10, Milestone 8)

Previously, at most one TIMESTAMP column per table could be automatically initialized or updated to the current date and time. This restriction has been lifted. Any TIMESTAMP column definition can have any combination of DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP clauses. In addition, these clauses now can be used with DATETIME column definitions. For more information, see Automatic Initialization and Updating for TIMESTAMP and DATETIME.

**Comment by skerbis** [comment]
REDAXO 5.6.5
PHP 7.2.13
MySQL5.5.62
AddOn-Version: 1.1.2
Gleicher Fehler

**Comment by skerbis** [comment]
Bitte diese Bedingung in die package.yml aufnehmen

**Comment by rkemmere** [comment]
Ich schau es mir mal an, ob es eine Möglichkeit gibt das mit zwei Timestamps zu umgehen.

**Comment by rkemmere** [comment]
Wir haben die Datefelder nochmal überarbeitet und reduziert.
