### ISSUE TITLE
Gültigkeitsdauer von SSL-Zertifikaten im Blick behalten

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/project_manager#11]
https://stackoverflow.com/questions/6863948/how-to-get-expiry-date-from-the-ssl-certificate-file-in-php

Wie wäre es, wenn Domains auch die Gültigkeitsdauer von SSL-Zertifikaten im Blick haben? Es gibt noch genügend Hoster, leider, bei denen die Erneureung der Zertifikate nicht automatisch erfolgen kann. Oder bspw., wenn die Domain extern gehostet ist.

**Comment by rkemmere** [comment]
Find ich eine gute Idee und wird mit aufgenommen.

**Comment by rkemmere** [comment]
Ist in der nächsten Version mit drin.

**Comment by alexplusde** [comment]
Klasse. Wir steigen dann von Hello um und dann schau ich, ob wir uns gut beteiligen können.

**Comment by staabm** [comment]
Wo genau ist das implementiert?

**Comment by rkemmere** [comment]
Im Plugin Hosting gibt es in der Übersicht eine Darstellung mit Gültigkeitsdauer.

**Comment by staabm** [comment]
Ich meinte, wo ist die implementierung die konkret das technisch ausliest? Welche codestelle?

**Comment by rkemmere** [comment]
https://github.com/FriendsOfREDAXO/project_manager/blob/ea2830b4f9dcf2f8e6e14cf62a8bec8c0fa987ea/plugins/hosting/lib/project-manager-hosting.cronjob.php#L51

**Comment by staabm** [comment]
Danke 🙏
