### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/project_manager#12]
in der dev-Version bei uns haben wir eine Suche bzw. einen Filter realisiert. Wie wäre es damit?

![image](https://user-images.githubusercontent.com/3855487/48848026-4782b280-eda3-11e8-9783-23c9e69b2501.png)

**Comment by alexplusde** [comment]
Nochmals zur Frage: Wäre eine Umstellung auf YForm gewünscht (hat die Suche von Haus aus) oder bleibt es bei rex_form?

**Comment by rkemmere** [comment]
Ich denke hier sollte man die YForm 3 abwarten und dann ggf. eine Umstellung machen. Alternativ würde ich die Suche mit einbauen.
