### ISSUE TITLE
Deprecated-Warnung bei manuellem Ausführen des Hosting-Cronjobs

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/project_manager#14]
Beim manuellen Ausführen des Hosting-Cronjobs kommt bei Verwendung von PHP 7.1.23 folgende Warnung:

```
Deprecated: idn_to_ascii() [function.idn-to-ascii]: INTL_IDNA_VARIANT_2003 is deprecated in 
/.. .. ../redaxo/src/addons/project_manager/plugins/hosting/lib/project-manager-hosting.cronjob.php on line 27
```

**Comment by staabm** [comment]
Laut doku http://php.net/manual/en/function.idn-to-ascii.php

Sollte vermutlich INTL_IDNA_VARIANT_UTS46 verwendet werden

Ungetestet

**Comment by rkemmere** [comment]
Ist im nächsten Update mit drin.
Danke!
