### ISSUE TITLE
Projekte: Tags vergeben

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/project_manager#18]
Es gibt ein Beschriftungsfeld, allerdings würden wir gerne projektintern auch noch Tags vergeben, um Kunden auf bestimmte Weise einzuteilen. das haben wir so gelöst:

![image](https://user-images.githubusercontent.com/3855487/50398461-0aca2280-0778-11e9-8521-b37cf4fe7fee.png)

Wie wäre das?

**Comment by rkemmere** [comment]
Braucht Ihr dort eine Selectbox mit vordefinierten Werten oder geht dort auch eine Tagliste?

[https://www.jqueryscript.net/demo/Bootstrap-4-Tag-Input-Plugin-jQuery/](https://www.jqueryscript.net/demo/Bootstrap-4-Tag-Input-Plugin-jQuery/)

**Comment by alexplusde** [comment]
Tagliste wäre auch schön.

**Comment by rkemmere** [comment]
Ist in der nächsten Version eingebaut.
