### ISSUE TITLE
Hosting/Pagespeed-aktualisieren hängt sich auf

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/project_manager#19]
Bei 368 Projekten, man klickt den aktualisieren-Knopf (was cool ist) und er dreht sich - doch dann passiert nichts. Beim Hosting lief wohl alles durch, bei Pagespeed hat er evtl. ein paar Datensätze aktualisiert.

Ich hatte das deswegen mal so gelöst, dass die nicht alle in einem Rutsch generiert werden, sondern Scheibchenweise. Das hängt eben auch sehr vom Typ des Servers ab. 

Kann man das irgendwie sinnvoll lösen?

**Comment by alexplusde** [comment]
Ich glaube, es liegt wirklich an der Laufzeit. Starte ich den Projekt-Cronjob manuell, erhalte ich:
> Maximum execution time of 30 seconds exceeded

Deshalb habe ich die nie in einem Rutsch abgerufen, sondern Paketweise sortiert nach den ältesten und ggf. nicht erfolgreichen Abruf-Versuchen.

**Comment by rkemmere** [comment]
Wir haben den Pagespeed Cron heute umgebaut. Brauchen aber bei 100 Projekten noch 40 Sekunden. Was aber beim Server Plugin kein Problem ist, da hier die max execution time ja angepasst werden kann.

Der Hosting Cron braucht einen Sleep da die API sonst die IP sperrt. Das ist ja nach Menge der Projekte aber auch unterhalb von 60 Sekunden erledigt.

**Comment by rkemmere** [comment]
Wieviele Projekte habt ihr denn alle so drin?
