### ISSUE TITLE
Paginierung + Table Sorter

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/project_manager#23]
In der momentanen Umsetzung kann der Table Sorter nur die aktuell dargestellten Projekte sortieren. Da die Darstellung im Moment auf 100 begrenzt ist, wäre es gut, wenn der Tablesorter entweder die Daten per AJAX nachlädt und sortiert, oder die Begrenzung von 100 aufgehoben wird.

performancetechnisch sollten 500-1000 Einträge auf einer Seite eigentlich kein Problem darstellen.

**Comment by rkemmere** [comment]
Limitierung ist rausgenommen im nächsten Update.

**Comment by rkemmere** [comment]
Im Moment haben wir knapp 100 Projekte drin und da ist es noch übersichtlich genug.
Paginierung kann ich bei Bedarf einbauen. Da macht es dann vielleicht Sinn das per Konfiguration zu lösen.
z.B. Itemsperpage
