### ISSUE TITLE
Screenshots für die Detailseite eines Projekts / Hover zur Vorschau

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/project_manager#24]
Screenshots lassen sich ebenfalls über die Pagespeed-API abrufen. Diese kann man bspw. auf der Detailseite eines Projekts ausgeben, um das ganze optisch etwas aufzuhübschen.

`'https://www.googleapis.com/pagespeedonline/v4/runPagespeed?filter_third_party_resources=false&locale=de_DE&screenshot=true&snapshots=true&strategy=desktop&key=###########&url='.urlencode($project['url']);`

**Comment by skerbis** [comment]
Alternativ skaliertes iframe?

**Comment by rkemmere** [comment]
Screenshot ist nun per Hook des Pagespeed Plugin eingebunden. Änderung in der nächsten Version.
