### ISSUE TITLE
Roter Kasten Versionen :: obwohl alles in Ordnung

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/project_manager#25]
Die aktuelle Farbe rot für die Versionsauflistung suggeriert, dass etwas nicht in Ordnung ist. 
Rot bitte nur verwenden, wenn eine Bedingung nicht erfüllt ist. 
Wenn alles ok, grün?

**Comment by olien** [comment]
Und dann würde es doch reichen wenn der Text eingefärbt wird...

**Comment by skerbis** [comment]
oder so

**Comment by rkemmere** [comment]
Ich finde die reine Textfarbe zu wenig. Testes es bei Euch mal bitte per Inspektor.
Wer möchte kann es ja per Theme CSS wieder überschreiben:

**td.alert-danger.project-manager, .tablesorter-default td.alert-danger**
