### ISSUE TITLE
AddOn-Key mit FOR verknüpfen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/project_manager#36]
Der AddOn-Key sollte mit Friends Of REDAXO verknüpft sein und ist aktuell aber mit manetage verknüpft. Jemand vom Core-Team kann ihn neu zuweisen.

https://redaxo.org/download/addons/project_manager/

(API-Key von FOR kann im Slack erfragt werden. Zum Publizieren neuer Releases.)

**Comment by tbaddade** [comment]
> Der AddOn-Key sollte mit Friends Of REDAXO verknüpft sein

ist erledigt

**Comment by tbaddade** [comment]
@schuer machst du auch hier gleich die package.yml mit?

**Comment by pschuchmann** [comment]
PR ist gemerged!
