### ISSUE TITLE
Konflikt mit dem maintenance AddOn

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/project_manager#38]
Wenn ich das maintenance AddOn bei einer Seite, die "überwacht" wird aktiviert habe funktionieren die cronjobs nicht richtig. 

Wenn ich auf der Seite project_manager/server/overview die Projektdaten aktualisieren möchte wird der Vorgang auch nicht beendet.

**Comment by pschuchmann** [comment]
Hey, 

ich schreib es hier nochmal, dass es auch für die Allgemeinheit zugänglich ist. Die einfachste Variante an dieser Stelle wäre im Maintenance Addon in der zu überwachenden Instanz im Reiter Frontend die IP des Servers einzutragen auf dem der Project Manager installiert ist. Das sollte es dem Projekt Manager an für sich ermöglichen die Daten entsprechend abzurufen. 

Vielleicht hat @skerbis noch eine andere Idee?!

**Comment by skerbis** [comment]
Dafür ist die IP da. Sicher könnte man noch über einen Token oder so nachdenken. Aber das verkompliziert die Sache ja. Das Projekt-Addon ohne Schutz drauf los zu lassen wäre töricht.

**Comment by pschuchmann** [comment]
Ja, denke ich auch. @olien, kannst du kurz Feedback geben, ob das so praktikabel für dich ist?

**Comment by rkemmere** [comment]
Stimme dem auch zu. Will man das der Projekt Manager eine Seite überwacht, welche sich im Maintenance Modus befindet, muss die Server IP vom Projekt Manager eingetragen werden / sein.

**Comment by olien** [comment]
Passt und funktioniert super. Danke an alle!
