### ISSUE TITLE
Wahnwitzige Anzahl von Updates in Projektübersicht angezeigt

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/project_manager#40]
In der "Projekte"-Übersicht werden 29 Updates angezeigt, obwohl im besagten Projekt alle Updates durchgeführt wurden  ("Installer > Vorhandene aktualisieren" ist leer).

Redaxo: 5.10.0 (Client+Server)
Projekt Manager: 1.2.14 (Client+Server)

**Comment by isospin** [comment]
das kann ich bestätigen. auf der übersichtsseite wird eine falsche update anzahl angezeigt. in der detailasicht stimmt die anzahl der gefundenen updates...

**Comment by rolandsee** [comment]
Yep, ist mir eben auch aufgefallen. Die Angabe in der Listenansicht ist falsch, in der Detailansicht passt die Info.

**Comment by rkemmere** [comment]
Ach, da muss bei einem anderen Fix mit Oli dieser hier als Bug reingekommen sein. Ich kümmere mich drum.

**Comment by rkemmere** [comment]
Eine Klammer falsch!

Fix in 1.2.15 im Installer.

**Comment by alexwenz** [comment]
Vielen Dank!
