### ISSUE TITLE
Daten werden nicht mehr aktualisiert

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/project_manager#41]
Kann es an der MySQL Version liegen?

<details>
<summary>System report (REDAXO 5.10.0, PHP 7.3.16)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.10.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.16     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MySQL 5.5.60                   |
| Character set | utf8                           |
|       Warning | Die verwendete MySQL Version 5.5.60 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/13.0.5 |
|      Protocol | HTTP/1.1      |
|         HTTPS | yes           |

| Packages                  |            |
| ------------------------: | :--------- |
|                   adminer | 1.8.1      |
|                    backup | 2.6.0      |
|                  be_style | 2.10.0     |
|       be_style/customizer | 2.10.0     |
|           be_style/redaxo | 2.10.0     |
|                   cronjob | 2.7.0      |
|                 developer | 3.8.0      |
|                   install | 2.7.0      |
|             media_manager | 2.9.0      |
|                 mediapool | 2.8.0      |
|                  metainfo | 2.7.0      |
|             modulsammlung | 4.13.4     |
|                 phpmailer | 2.8.0      |
|           project_manager | 1.2.14     |
|   project_manager/hosting | 1.0.4      |
| project_manager/pagespeed | 1.2.1      |
|    project_manager/server | 1.2.8      |
|                 structure | 2.10.0     |
|         structure/content | 2.10.0     |
|                     theme | 1.1.1      |
|                     users | 2.6.1      |
|                      ycom | 4.0.1      |
|                 ycom/auth | 4.0.1      |
|                 ycom/docs | 4.0.1      |
|                ycom/group | 4.0.1      |
|                     yform | 3.3.1      |
|                yform/docs | 3.3.1      |
|               yform/email | 3.3.1      |
|             yform/manager | 3.3.1      |
|               yform/tools | 3.3.1      |
|                  yrewrite | 2.6        |

</details>

**Comment by olien** [comment]
Hm. Geht wieder.... Lag wohl an mir...

**Comment by olien** [comment]
Doch nicht. Ausserdem werden Updates angezeigt wo keine sind...

**Comment by rkemmere** [comment]
@olien besteht hier noch Handlungsbedarf? Weil bei uns wird alles richtig angezeigt.

**Comment by olien** [comment]
Hab gerade bei mir geguckt. Sieht gut aus. ich mach mal zu. Danke für die Nachfrage!
