### ISSUE TITLE
Deprecated / rex_exception ??

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/project_manager#43]
![image](https://user-images.githubusercontent.com/330516/78328766-40b3a480-7580-11ea-8478-7b30ff8aa1ce.png)

**Comment by pschuchmann** [comment]
https://www.php.net/manual/de/function.idn-to-ascii.php

Da hat sich der Default mit neueren PHP Versionen geändert. Sollten wir demnächst anpassen @rkemmere

**Comment by rkemmere** [comment]
Die rex_exeption hat mit der PHP Version nichts zu tun. Hier scheint auf dem Server einfach nicht alles sauber installiert worden zu sein.

**Comment by olien** [comment]
Könntest Du was fehlt auf dem Server?

**Comment by pschuchmann** [comment]
Die rex_exception wird durch den Api Call geworfen, vermutlich wegen der fehlerhaften Domain (SSL/Non-SSL, www/Non-www).

Aber die deprecated Warning kommt definitiv von der PHP Version. Grundsätzlich sollte an der Stelle aber alles wie gewohnt laufen.

@olien wir hatten ja gestern nochmal geschaut, die Dateien sind alle da, aber vermutlich wurde der Aufruf einfach nur geblockt. Oder hast du den Fehler wieder im Log?

**Comment by olien** [comment]
Hab den Fehler wieder im Log. da ich aber der einzige bin würde ich hier mal schliessen....

**Comment by pschuchmann** [comment]
Schau bitte nochmal im client Plugin, ob der Api Call wirklich da ist. Der müsste unter plugins/client/lib liegen und `rex_api_project_manager` heißen. Falls nicht, leg die Klasse nochmal händisch dort ab. Dann ist vermutlich beim Installieren/Updaten etwas schief gegangen.

https://github.com/FriendsOfREDAXO/project_manager/blob/09389d89ccaf48fd168662d01837ad4ec9b2950c/plugins/client/lib/rex_api_project_manager.php

Sag nochmal Bescheid. Ich suche derweil nochmal im Core, wann die Fehlermeldung kommt.

**Comment by olien** [comment]
Die Datei ist da. Ich würde hier trotzdem keine Zeit mehr investieren sofern der Fehler nicht nochmal irgendwo auftaucht.
