### ISSUE TITLE
Link "Projektdaten aktualisieren" nach Hinzufügen falsch

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#47]
Wenn man direkt nach dem Hinzufügen eines neuen Projektes den Link "Projektdaten aktualisieren" anklickt, wird das zuletzt angelegte Projekt zum Speichern als neuer Eintrag (Duplikat) geöffnet und das Formular mitsamt Fehlermeldung angezeigt.

Redaxo 5.11.1
Project_Manager 1.2.15

**Comment by rkemmere** [comment]
Fixed in project_manager  1.2.16  /  server 1.2.10
