### ISSUE TITLE
Projekte abrufen, welche auf Subdomains installiert sind

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#48]
Es wäre toll, wenn man auch Projekte abrufen könnte, welche auf Subdomains installiert und aufrufbar sind.

Aktuell wird mir bei einem Projekt, welches auf einer Subdomain läuft, nichts abegrufen.
Bei Status steht nur ein rotes Dreieck mit Ausrufezeichen.

**Comment by rkemmere** [comment]
Sicher das die Subdomain sauber erreichbar ist und auch keinen htaccess Schutz oder Maintenance Mode aktiv hat. 

Weil ich habe es eben getestet und es klappt bei mir ohne Probleme.

**Comment by iceman-fx** [comment]
Ja. Alles in Ordnung.
Der Aufruf ist neu.personal-partner.eu

Kein maintanance oder PW Schutz.

**Comment by iceman-fx** [comment]
Problem gefunden...
Eingestellt hatte ich ssl aktiv, aber die Webseite hat noch kein aktives ssl Zertifikat.
