### ISSUE TITLE
Rex-Api Aufruf nicht möglich, wenn index.php dex Clients nicht die Startdatei ist

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#50]
Der Aufruf der Api erfolgt ja über http://www.domain.de/?rex-api-call=project_manager&api_key=<api_key>.

Bei einigen Projekten, gibt es eine index.html, welche als Vorstartseite fungiert und damit die index.php von Redaxo erst im 2. Schritt genutzt/geladen wird.
Damit greift natürlich nicht der Rex-Api-Aufruf.

Es wäre vielleicht sinnvoll, die Aufruf-URL ändern zu können oder immer direkt auf die index.php zu legen:
http://www.domain.de/index.php?rex-api-call=project_manager&api_key=<api_key>

**Comment by rkemmere** [comment]
Fixed in project_manger 1.2.16 / server 1.2.10

**Comment by iceman-fx** [comment]
Hi.
Ich habe es soeben mit der aktuellen Version probiert.
Leider keine Änderung am Ergebnis.

**Comment by iceman-fx** [comment]
Fehler in https://github.com/FriendsOfREDAXO/project_manager/blob/master/plugins/server/lib/rex_api_project_manager_server.php (Zeile 95) gefunden:

$url = $protocol.urlencode($domain)."?rex-api-call=project_manager&api_key=".$api_key.'&t='.$timestamp;

Hier fehlt noch die index.php.

**Comment by rkemmere** [comment]
fixed 1.3 / server 1.3
