### ISSUE TITLE
Legende oder Hilfe zur Erklärung der Symbole in den Übersichten

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#51]
Mir ist z.B. aktuell nicht ganz klar, warum bei einigen Projekten bei Status ein rotes Dreieck steht und bei anderen nicht, obwohl alle Updates eingespeilt sind, die PHP-Version gleich ist und im Syslog nix steht.

Ein kurze Erklärung des Grundes der Symboldarstellung wäre daher zweckdienlich.

**Comment by rkemmere** [comment]
Das wird eigentlich nur angezeigt wenn entweder Updates vorhanden sind oder im Syslog ein Eintrag ist.
Bei unseren 100 Projekten funktioniert das auch so.

**Comment by iceman-fx** [comment]
Vielleicht macht es noch Sinn, eine Fehlermeldung irgendwo auszugeben/aufzuklappen, warum denn jetzt da ein Fehler ist und welcher Fehler.

**Comment by iceman-fx** [comment]
Evtl. könnte man eine kurze Info als Hover-Text beim Statussymbol anzeigen.

**Comment by iceman-fx** [comment]
Hallo Ronny,
ich habe nach wie vor das Problem, dass der Status iner Übersicht mal einen Haken hat und ein anderes Mal wieder eine Warnung. Dabei ist egal, ob im Syslog Meldungen stehen oder nicht.

Ich weiß einfach immer nicht, warum dort manchmal ein Warnung kommt.

Ein Hinweis oder eine Legende wäre schon sehr sinnvoll, da es sich mir nicht erschließt, was der Status tatsächlich nun mir sagen will.

**Comment by rkemmere** [comment]
Status 0 _ fa-question text-warning _ Falscher API-Schlüssel
Status -1 _ fa-exclamation-triangle text-danger _ JSON Error
Status 1 _ fa-check text-success Abruf der Client Daten ok

**Comment by rkemmere** [comment]
Syslog 1 _ fa-check text-success   Keine Daten im Syslog
Syslog 2 _ fa-exclamation-triangle text-danger  Syslogeintrag gefunden (Außer info)

**Comment by iceman-fx** [comment]
OK, dann erhalte öfters den Status -1 angezeigt.
fa-exclamation-triangle text-danger

**Comment by iceman-fx** [comment]
Vielleicht machst Du einfach ein kleines title="" Tag an das Symbol, welches kurz beschreibt, was der Status aussagt.

**Comment by rkemmere** [comment]
Ja ich mach jeweils ein Title Attribute mit rein und zeige die Info mit an.

**Comment by iceman-fx** [comment]
Super.

**Comment by rkemmere** [comment]
Enthalten in 1.3.6
