### ISSUE TITLE
Link zum Redaxo-Login direkt in der Projektübersicht

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#52]
In der Projektübersicht wäre anstatt oder zusätzlich zum Link zur Projekt-Homepage noch ein Link direkt zum Redaxo-Login toll.

**Comment by rkemmere** [comment]
Ich erweitere den Check auf /redaxo. Wenn dieser einen 200er zurückgibt, dann setzte ich ein Flag in der Datenbank. In der Listenansicht gebe ich dann ein "R" neben dem Domainnamen aus, der dann den /redaxo Link baut.

**Comment by olien** [comment]
Top

**Comment by rkemmere** [comment]
Wird nun vom Client übertragen und wenn vorhanden in der Listen- und Detailansicht angezeigt.
