### ISSUE TITLE
Feld "Wartungsvertrag" wird nicht gespeichert

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#55]
Das neue Feld Wartungsvertrag wird bei Auswahl ja nicht gespeichert.
Es wird beim nächsten Aufruf wieder als Nein angezeigt.

**Comment by rkemmere** [comment]
Wir bei mir gespeichert. Bitte prüfe mal ob das DB Feld "maintenance" bei dir in der Tabelle "project_manager_domain" ist.

**Comment by iceman-fx** [comment]
Nein, das Feld maintenance gibt es in keiner der Tabellen.

**Comment by rkemmere** [comment]
Dann den install des Server Plugins nochmal ausführen, dann sollte das erstellt werden.

**Comment by iceman-fx** [comment]
Hat geklappt. Geht jetzt. Danke.

**Comment by rkemmere** [comment]
Ok. Top.
