### ISSUE TITLE
Weisse Seite nach Update

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/project_manager#56]
Nach dem Update auf Version 1.3.0 erhalte ich nur eine weisse Seite wenn ich /redaxo/index.php?page=project_manager/server/overview aufrufen möchte.

Im Log steht "nur":

![image](https://user-images.githubusercontent.com/330516/105973890-8f8d7600-608d-11eb-971f-6bc90f2308b7.png)

REDAXO + AddOns = Aktuellste Versionen

**Comment by rkemmere** [comment]
Fixed in 1.3.1
