### ISSUE TITLE
Neues Projekt wird nicht gespeichert

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/project_manager#57]
Hi,
ich verwende aktuell den Projektmanager 1.3.0 unter Redaxo 5.11.2, PHP 7.4 und mySql 5.7.
Ausgangspunkt: Ich habe aktuell 38 Projekte im Projektmanager eingetragen.
Beim Versuch, das 39te Projekt einzutragen, erscheint zwar die grüne Meldung "Projekt wurde gespeichert". Tatsächlich ist aber kein Eintrag in der DB erfolgt. Die Tabelle ist unverändert. Im Log ist kein Hinweis auf einen möglichen Fehler zu finden.
Den Fehler konnte ich am localhost sowie auf dem Live-System nachvollziehen.

![projectmanager-redaxo](https://user-images.githubusercontent.com/4113894/107767922-fbcad380-6d35-11eb-8f54-df911c666b7a.jpg)

**Comment by rkemmere** [comment]
Bitte mal in Slack kommen, dann prüfe ich das direkt.

**Comment by rkemmere** [comment]
Reinstall des Server Plugins hat geholfen.

In der nächsten Version wird die Update Routine nochmal überarbeitet.
