### ISSUE TITLE
Übersicht Syslog-Info nur bei Fehlern

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#61]
Es wäre evtl. sinnvoll, wenn das rote Ausrufezeichen bei Syslog in der projektübersicht nur angezeigt wird, wenn auch wirklich Warnings oder Notices vorliegen.

Aktuell wird auch bei reinen Info-Typ (z.B. Addon Update installiert) das rote Ausrufezeichen angezeigt, was etwas irreführend ist.

**Comment by rkemmere** [comment]
Plane ich gerne mit ein. Die Update Infos kamen ja erst in den letzten Redaxo Versionen dazu,
