### ISSUE TITLE
Hostingbereich wirft SQL-Fehler in aktueller PM-Version

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#66]
03.12.2021 08:32:23
rex_sql_exception

Error while executing statement "SELECT COUNT(*) AS `rows` FROM (SELECT * FROM (SELECT * FROM rex_project_manager_domain ORDER BY domain ASC) AS DLEFT JOIN (SELECT status as status_hosting, createdate as createdate_hosting, domain, ip, rawFROM rex_project_manager_domain_hosting) as HON D.domain = H.domainGROUP by D.domainORDER BY name ASC) t": SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'domain'

redaxo/src/core/lib/sql/sql.php | 455

**Comment by rkemmere** [comment]
Die Abfrage gibt es in nicht?! Sag mal bitte die Codestelle wo das passieren soll.

**Comment by iceman-fx** [comment]
Stack frames (22)
21
rex_sql_exception 
…/redaxo/src/core/lib/sql/sql.php455
20
PDOException 
…/redaxo/src/core/lib/sql/sql.php442
19
PDO query
…/redaxo/src/core/lib/sql/sql.php442
18
rex_sql {closure}
…/redaxo/src/core/lib/util/timer.php57
17
rex_timer measure
…/redaxo/src/core/lib/sql/sql.php450
16
rex_sql setQuery
…/redaxo/src/core/lib/list.php189
15
rex_list __construct
…/redaxo/src/core/lib/list.php226
14
rex_list factory
…/redaxo/src/addons/project_manager/plugins/hosting/pages/project_manager.hosting.overview.php40
13
 include
…/redaxo/src/core/lib/packages/package.php285
12
rex_package includeFile
…/redaxo/src/core/lib/be/controller.php485
11
rex_be_controller {closure}
…/redaxo/src/core/lib/util/timer.php57
10
rex_timer measure
…/redaxo/src/core/lib/be/controller.php486
9
rex_be_controller includePath
…/redaxo/src/core/lib/be/controller.php432
8
rex_be_controller includeCurrentPageSubPath
…/redaxo/src/addons/project_manager/pages/index.php14
7
 include
…/redaxo/src/core/lib/packages/package.php285
6
rex_package includeFile
…/redaxo/src/core/lib/be/controller.php485
5
rex_be_controller {closure}
…/redaxo/src/core/lib/util/timer.php57
4
rex_timer measure
…/redaxo/src/core/lib/be/controller.php486
3
rex_be_controller includePath
…/redaxo/src/core/lib/be/controller.php415
2
rex_be_controller includeCurrentPage
…/redaxo/src/core/backend.php238
1
 require
…/redaxo/src/core/boot.php143
0
 require
…/redaxo/index.php9

**Comment by rkemmere** [comment]
Ändere mal Zeile 16 so ab: 

`SELECT * FROM (SELECT * FROM  '. rex::getTable('project_manager_domain') . ' ORDER BY d.domain ASC) AS D `

**Comment by iceman-fx** [comment]
Ändert leider nichts.

Error while executing statement "SELECT * FROM (SELECT * FROM rex_project_manager_domain ORDER BY d.domain ASC) AS D LEFT JOIN ( SELECT status as status_hosting, createdate as createdate_hosting, domain, ip, raw FROM rex_project_manager_domain_hosting ) as H ON D.domain = H.domain GROUP by D.domain ORDER BY name ASC ": SQLSTATE[42S22]: Column not found: 1054 Unknown column 'd.domain' in 'order clause'

**Comment by rkemmere** [comment]
Fix in 1.3.6 / Hosting und Pagespeed Plugin
