### ISSUE TITLE
Berechnung der Updates verkehrt?

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/project_manager#71]
Client:

![image](https://user-images.githubusercontent.com/3855487/151707100-966c025a-de78-4849-92b0-6941c0cb3c84.png)

Eintrag im Server:

![image](https://user-images.githubusercontent.com/3855487/151707141-e3ca968d-1065-4f25-a6e8-9de2c1779997.png)

**Comment by rkemmere** [comment]
Hab es eben auch mit einer Version getestet, die jetzt aktuelle alle Updates installiert hat. Wir bei mir als - in der Übersicht angezeigt und in der Detailseite steht, "Updates (0)"

![image](https://user-images.githubusercontent.com/2286625/151708245-139a5970-0e30-42b4-a628-7f9f0fdec610.png)
