### ISSUE TITLE
SSL-Status wird nicht mehr abgefragt

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/project_manager#72]
![image](https://user-images.githubusercontent.com/3855487/151707151-eba59daf-4d61-4fd2-9c01-012716a9d072.png)

**Comment by rkemmere** [comment]
Alex was ist mit Deiner Version los? Bei mir geht mit der aktuellen Version alles.

**Comment by rolandsee** [comment]
Hmm, bei mir (R5.13.2, PHP 8.0, Projektmanager 1.37) sieht es nun auch so aus wie bei Alex:
![image](https://user-images.githubusercontent.com/4113894/162951705-71635f1e-4856-4cf0-ab1f-258a0888a7d7.png)
Im Editmode lässt sich SSL auch nicht mehr bearbeiten:
![image](https://user-images.githubusercontent.com/4113894/162951863-60c9750e-03fd-4ff7-a8a8-b0c5071a381d.png)

**Comment by rkemmere** [comment]
YFORM Version auf dem Server wo das Addon als Server läuft ist vermutlich 4.x?
Dafür müssen noch Anpassungen gemacht werden.

**Comment by rolandsee** [comment]
Hi Ronny, ja, du hast Recht. Es läuft YForm 4.0.2. Danke für den Hinweis.

**Comment by rkemmere** [comment]
1.3.8 läuft jetzt auch mit YFORM 4 im Hintergrund.
