### ISSUE TITLE
Mindestanforderungen - REDAXO 5 wird nicht mehr gehighlightet

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/project_manager#73]
Die sollten jetzt rot gefärbt sein.

![image](https://user-images.githubusercontent.com/3855487/151707213-4c7c6b29-e991-4fc9-aedf-f68e3edb086e.png)

Was ist eigentlich mit diesem Addon passiert, das hat doch alles mal funktioniert?!

**Comment by rkemmere** [comment]
Geht in der aktuellen Version. Gerade auf einer frischen Redaxo Version das Addon als Server installiert und probiert.

**Comment by alxndr-w** [comment]
Wenn du Zeit hast, können wir uns das mal bei mir live anschauen.
