### ISSUE TITLE
Kompatibilität mit maintenance-Addon

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/project_manager#74]
Das Addon sollte auch Seiten im Maintenance-Modus richtig abfragen. Das Freigeben der Server-IP im Maintenance-Modus scheint nicht zu genügen.

**Comment by rkemmere** [comment]
Funktioniert, wenn auf dem Client im Maintenance Modus die IP vom Server eingetragen wird, auf dem die Projektverwaltung läuft. Habe eben abrufen und löschen des syslogs getestet.

**Comment by rkemmere** [comment]
Test liegt auf einem anderen Server und im Maintenance ist die IP der Projektverwaltung hinterlegt.

![image](https://user-images.githubusercontent.com/2286625/151708307-cfc41c2e-044c-49f7-be94-51346ef998f2.png)

**Comment by rkemmere** [comment]
In 1.4 können Parameter wie secret=passwort übergeben werden.
