### ISSUE TITLE
Icon "Wartungsvertrag"

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/project_manager#77]
Mein Chef ist rot/grün Blind und kann nicht unterscheiden ob ein Projekt einen Wartungsvertrag hat oder nicht. Wäre es hier möglich einfach auch das Häkchen (wie bei Status) zu nutzen? (Kein Icon sofern es keinen WV gibt)

**Comment by rkemmere** [comment]
Moin Oli, wir können das anpassen. 

Fragezeichen: Nicht gesetzt
Minus: Keine Wartungsvertrag
Dokument: Wartungsvertrag

Würde das passen?

**Comment by olien** [comment]
Ja. Super. Danke sehr!

**Comment by rkemmere** [comment]
Fix in 1.5.0
