### ISSUE TITLE
Einige Fehlerausgaben in der Projekteübersicht mit der aktuellen Version

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/project_manager#82]
Mit werden in der Übersicht einige kleinere Fehler ausgeben, nachdem ich manuell auf Aktualisieren geklickt habe und er damit fertig war:

Warning: Undefined array key "cms_version" in redaxo/src/addons/project_manager/plugins/server/pages/project_manager.server.overview.php on line 262
Warning: Undefined array key "article" in redaxo/src/addons/project_manager/plugins/server/pages/project_manager.server.overview.php on line 273
Warning: Trying to access array offset on value of type null in redaxo/src/addons/project_manager/plugins/server/pages/project_manager.server.overview.php on line 273
Warning: Trying to access array offset on value of type null in redaxo/src/addons/project_manager/plugins/server/pages/project_manager.server.overview.php on line 273
Warning: Undefined array key "cms_version" in redaxo/src/addons/project_manager/plugins/server/pages/project_manager.server.overview.php on line 359
Warning: Undefined array key "cms_version" in redaxo/src/addons/project_manager/plugins/server/pages/project_manager.server.overview.php on line 360

**Comment by rkemmere** [comment]
Welche Redaxo Version / PHP Version wird dort eingesetzt?

**Comment by iceman-fx** [comment]
REDAXO: 5.14.2
PHP: 7.4.30

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/project_manager/commit/017092dcaba01eba07c7014d4af7d781b7576c48
